### ISSUE TITLE
latest Aurelia version

### ISSUE THREAD

**Issue by opcodewriter** [gist-run/gist-run#22]
are these the correct scripts to use for the latest Aurelia in aurelia-bundle?
```
    <script src="https://cdn.rawgit.com/jdanyow/aurelia-bundle/master/jspm_packages/system.js"></script>
    <script src="https://cdn.rawgit.com/jdanyow/aurelia-bundle/master/config.js"></script>
```

**Comment by jdanyow** [comment]
the latest aurelia bundle is here: https://gist.run/?id=7542e061bc940cde506b
```html
<script src="https://cdn.rawgit.com/jdanyow/aurelia-bundle/v1.0.3/jspm_packages/system.js"></script>
 <script src="https://cdn.rawgit.com/jdanyow/aurelia-bundle/v1.0.3/config.js"></script>
```

It's pretty recent- some of the updates from the last week are not yet in there.  Will be updating it soon.

**Comment by niieani** [comment]
Would be great to get an update. Perhaps an automated build system would solve the problem of manual updates?

**Comment by jdanyow** [comment]
latest is here https://gist.run/?id=7542e061bc940cde506b

**Comment by karthickthangasamy** [comment]
while open the this latest Aurelia https://gist.run/?id=7542e061bc940cde506b getting the below console error.

```
/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
about:blank:1 Refused to display 'https://gist.host/' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.
https://gist.host/ Failed to load resource: the server responded with a status of 403 ()
```

**Comment by jdanyow** [comment]
That's an issue in gist.run- it's running an old build of Aurelia. Will be fixed next time I push a new build out.

The Aurelia gist IS up to date.  Safe to ignore that message for now.
