### ISSUE TITLE
Question, can I add other jspm libs to it?

### ISSUE THREAD

**Issue by vegarringdal** [gist-run/gist-run#26]
Question, can I add other jspm libs to gistrun page?
Would like to add sortablejs, and mustache so I could test something.

**Comment by jdanyow** [comment]
definitely- just add a script tag like this: `<script src="https://some-cdn-that-you-like/sortable.js"></script>`

Or you could even use something like `require.config({ paths: { sortable: 'https://some-cdn-that-you-like/sortable.js' }})`
