### ISSUE TITLE
Do GistRun links ever expire?

### ISSUE THREAD

**Issue by lmj0011** [gist-run/gist-run#28]
if GistRun links do not last forever, then how long until they expire?

**Comment by jdanyow** [comment]
They last forever- unless you delete the GitHub Gist.  GistRun does not store any of your code- it's all stored in GitHub Gists.

**Comment by lmj0011** [comment]
>They last forever- unless you delete the GitHub Gist. GistRun does not store any of your code- it's all stored in GitHub Gists.

Even if you don't sign in?

**Comment by jdanyow** [comment]
Yep- they're stored as a github gist.  If you're signed in they will be stored in your gists, otherwise they'll be saved as an anonymous gist.  This mirrors what would happen if you were to go to https://gist.github.com/ without signing in.
