### ISSUE TITLE
Does not work in Firefox

### ISSUE THREAD

**Issue by gheoan** [gist-run/gist-run#39]
Firefox 50.1.0

URL: https://gist.run/
Screenshot: ![screen shot 2017-01-17 at 17 00 57-fullpage](https://cloud.githubusercontent.com/assets/9906612/22025584/c3d69e94-dcd6-11e6-853a-c0de71a03bac.png)

I expect the iframe to display "Hello World!".

**Comment by jdanyow** [comment]
working for me:

![image](https://cloud.githubusercontent.com/assets/1306747/22031840/fa5b6520-dcaf-11e6-82c2-a0b8456bb68f.png)

What does the browser's network tab look like? And the console tab.

**Comment by jdanyow** [comment]
maybe it's a similar to this issue: https://github.com/aurelia/metadata/pull/48#issuecomment-267726063

![image](https://cloud.githubusercontent.com/assets/1306747/22032050/e00fda42-dcb0-11e6-8a1a-ab3ce1de5c38.png)

**Comment by gheoan** [comment]
The cause seems to be [this](https://bugzilla.mozilla.org/show_bug.cgi?id=1242056) bug in Firefox, because I can't reproduce this issue in a new Firefox profile.
