### ISSUE TITLE
Slots don't work in GistRun?

### ISSUE THREAD

**Issue by JoshMcCullough** [gist-run/gist-run#40]
While trying to debug why some slots weren't being filled in my application, I created a GistRun and found that the slots weren't filled there, either. Not sure if this is an issue with GistRun, or if I've missed something.

https://gist.run/?id=5989246fdf1d396e40b5ec3f00cd24f0

**Comment by hfitzwater** [comment]
This one is set up using a different set of packaged dependencies and it works.  Not sure why yet...

[https://gist.run/?id=8bf0404244d23843e010c943cbdfceab&sha=d23174a4326846e9aa76d9d2e631d30adff21d10](https://gist.run/?id=8bf0404244d23843e010c943cbdfceab&sha=d23174a4326846e9aa76d9d2e631d30adff21d10)

**Comment by JoshMcCullough** [comment]
Thanks @appleskin, you're a gentleman and a scholar. I'll leave this here anyway since it seems like there could be a problem with that version of `SystemJS`?

**Comment by jdanyow** [comment]
The gist in your first post is a fork of a really old aurelia gist/plunker that is not kept current.  The gist in your second post is a fork of https://gist.run/?id=7542e061bc940cde506b which is kept up to date.  Basically you want to fork this gist https://gist.run/?id=7542e061bc940cde506b when creating new aurelia gists.

**Comment by JoshMcCullough** [comment]
@jdanyow Thanks for clarifying.
