### ISSUE TITLE
gist.host is not working (CNAME Cross-User Banned)

### ISSUE THREAD

**Issue by gpetrioli** [gist-run/gist-run#41]
Visiting the page returns 

>Error 1014 Ray ID: 335db2be5d675ca5 • 2017-02-23 21:16:19 UTC
CNAME Cross-User Banned
What happened?
You've requested a page on a website that is part of the Cloudflare network. The host is configured as a CNAME across accounts on Cloudflare, which is prohibited by security policy.
What can I do?
If you are interested in learning more about Cloudflare, please visit our website.
Cloudflare Ray ID: 335db2be5d675ca5 • Your IP: <my.own.ip.address> • Performance & security by Cloudflare

which also means that the https://gist.run site can not run any gist.

**Comment by jdanyow** [comment]
working for me- where are you located?

**Comment by gpetrioli** [comment]
@jdanyow seems to be working now. I am from Europe (Greece).

**Comment by jdanyow** [comment]
Nice! Thanks for reporting.

Greece is beautiful- enjoy :+1:
